trigger:
- main

resources:
  repositories:
  - repository: lovable
    type: git
    name: lovable

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self          # Checks out the current pipeline repo
- checkout: lovable  # Checks out your "lovable" repo

- bash: echo "Hello World"
  displayName: 'Run Hello World Script'
