trigger:
- main

resources:
  repositories:
  - repository: lovable-repo
    type: git
    name: MyProject/lovable # Format is 'ProjectName/RepositoryName'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self          # Checks out the current pipeline repo
- checkout: lovable-repo  # Checks out your "lovable" repo

- bash: echo "Hello World"
  displayName: 'Run Hello World Script'
